version: "3"
services:

    sercnav:
        image: batrakunal/sercnav:latest
        container_name: sercnav
        restart: always
        ports:
         - "8000:80"

    systemitool:
        image: batrakunal/systemitool:latest
        container_name: systemitool
        restart: always
        ports:
         - "8001:80"
        volumes:
            - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    backend:
        image: batrakunal/sercbackend:test
        container_name: backend
        restart: always
        ports:
         - "8081:8000"

    prodbackend:
        image: batrakunal/sercbackend:latest
        container_name: prodbackend
        restart: always
        ports:
         - "8080:8000"

#    wwd:
#        image: batrakunal/wwd:latest
#        container_name: wwd
#        restart: always
    
#    airc:
#        image: batrakunal/airc_web:latest
#        container_name: airc_web
#        restart: always
        

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - sercnav
#            - wwd
            - systemitool
            - backend
            - prodbackend
#            - airc
